image: alpine:latest

#variables:

stages:
  - build

build:
  stage: build
  image: docker:git
  services:
  - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

    - docker build 
      --target importer 
      --tag "${CI_REGISTRY_IMAGE}/importer:$CI_COMMIT_SHORT_SHA" 
      --tag "${CI_REGISTRY_IMAGE}/importer:latest" 
      docker

    - docker push 
      "${CI_REGISTRY_IMAGE}/importer" 
      --all-tags

    - docker pull 
      "${CI_REGISTRY_IMAGE}/builder:latest" || true
    - docker build 
      --cache-from "${CI_REGISTRY_IMAGE}/builder:latest" 
      --tag "${CI_REGISTRY_IMAGE}/builder:$CI_COMMIT_SHORT_SHA" 
      --tag "${CI_REGISTRY_IMAGE}/builder:latest" docker
    - docker push 
      "${CI_REGISTRY_IMAGE}/builder" 
      --all-tags

  only:
    - branches
