services:
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../cdk/lib/www:/usr/share/nginx/html
      - ../workspace:/workspace

  terrasync:
    build:
      context: .
      dockerfile: Dockerfile.terrasync
    image: torstend/terrasync
    user: 1000:1000
    volumes:
      - $HOME/FlightGear/fgscenery:/fg
      - ../workspace:/workspace
    command: -t /workspace/scenery -u https://ukmirror.flightgear.org/fgscenery --left "6" --bottom "38" --top "42" --right "12"

  builder:
#    platform: linux/amd64
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PLATFORM: arm64
    image: ${DOCKER_IMAGE:?error}
    environment:
      FG_SCENERY: /workspace/scenery
      FG_ROOT: /app/fg_root
      OSM2CITY_PATH_TO_OUTPUT: /workspace/o2c-scenery
      OSM2CITY_PATH_TO_PACKED: /workspace/o2c-packed
      OVERPASS_URI: "https://overpass.kumi.systems/api/interpreter"
#      O2C_PROCESSES: 4
    deploy:
      resources:
        limits:
          memory: 8G
    volumes:
#      - ../osm2city:/app/osm2city
#      - ./params.ini:/app/params.ini
      - ./scripts:/app/scripts
      - ${FG_ROOT:?error}:/app/fg_root:ro
      - ../workspace:/workspace
    entrypoint:
      - /app/scripts/build.sh
# 2150376 killed
