services:
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../aws-ts/lib/www:/usr/share/nginx/html

  jupyter:
    image: jupyter/tensorflow-notebook:latest
    ports:
      - 8888:8888
    volumes:
      - ../jupyter-work:/home/jovyan

  postgres:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_USER: osm
      POSTGRES_DB: osm
      POSTGRES_PASSWORD: secret
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 4G

  curl:
    image: curlimages/curl
    user: 1000:1000
    volumes:
      - ../workspace:/workspace

  terrasync:
    build:
      context: .
      dockerfile: Dockerfile.terrasync
    image: torstend/terrasync
    user: 1000:1000
    volumes:
      - $HOME/FlightGear/fgscenery:/fg
      - ../workspace:/workspace
    command: -t /workspace/scenery -u https://ukmirror.flightgear.org/fgscenery --left "6" --bottom "38" --top "42" --right "12"

  importer:
    build:
      context: .
      dockerfile: Dockerfile
      target: importer
    image: t3r/cloudcity/importer
    volumes:
      - /tmp:/tmp
      - ./scripts:/app/scripts
      - ../workspace:/workspace
    command:
      - /app/scripts/import.sh
      - --input
      - /workspace/planet.osm.pbf
#      - --1x1
#      - e009n53
      - --tile
      - "3105763"
      - --database
      - osm
    environment:
      PGHOST: postgres
      PGUSER: osm
      PGDATABASE: osm
      PGPASSWORD: secret
      PGPORT: 5432

  builder:
#    platform: linux/amd64
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: registry.gitlab.com/t3r/cloudcity/builder:61075fbd
      #privileged: true
    environment:
      FG_SCENERY: /workspace/scenery
      FG_ROOT: /app/fg_root
      OSM2CITY_PATH_TO_OUTPUT: /workspace/o2c-scenery
      OSM2CITY_PATH_TO_PACKED: /workspace/o2c-packed
      OVERPASS_URI: "https://overpass.kumi.systems/api/interpreter"
#      O2C_PROCESSES: 4
    deploy:
      resources:
        limits:
          memory: 8G
    volumes:
#      - ../osm2city:/app/osm2city
#      - ./params.ini:/app/params.ini
      - ./scripts:/app/scripts
      - ${FG_ROOT:?error}:/app/fg_root:ro
      - ../workspace:/workspace
    entrypoint:
      - /app/scripts/build.sh
# 2150376 killed
